import { computeReadingStats } from "../src/utils/readingStats.js";
export const API_URL = "https://example.invalid";
let scenario = "populated";
export const setScenario = (value) => { scenario = value; };
const companies = [{ id: 1, nome: "Atlas Logística", segmento: "Distribuição", total_leituras: 3, cnpj: "", cidade: "Campinas", estado: "SP" }, { id: 2, nome: "Horizonte Armazéns", segmento: "Armazenagem", total_leituras: 1 }];
const readings = [1, 2, 3, 4].map((id) => ({ id, empresa_id: id === 4 ? 2 : 1, empresa: id === 4 ? "Horizonte Armazéns" : "Atlas Logística", nome_produto: ["Sensor óptico industrial", "Módulo de automação", "Unidade de controle", "Kit de manutenção"][id - 1], produto_id: `SKU-00${id}`, codigo_qr: `QA-${id}`, quantidade: id * 12, fragil: id === 1 ? "Sim" : "Não", local_lido: `Corredor A · posição 0${id}`, setor: "Recebimento", operador: "Operador de teste", status: "lido", criado_em: new Date().toISOString() }));
const operations = [{ id: 1, titulo: "Conferência do corredor A", empresa_nome: "Atlas Logística", status: "em_andamento", piloto: "Operador de teste", area_voo: "Recebimento", descricao: "Missão de demonstração visual. Nenhum drone conectado." }];
const operators = [{ id: 1, empresa_id: 1, nome: "Operador de teste", email: "qa@example.invalid", empresa_nome: "Atlas Logística", setor_nome: "Recebimento", permissoes: "leitura,operacoes" }];
const sectors = [{ id: 1, empresa_id: 1, nome: "Recebimento", empresa_nome: "Atlas Logística" }];
const alerts = [{ id: 1, tipo: "aviso", mensagem: "Conferir identificação da posição A-04", empresa_nome: "Atlas Logística", lido: false, criado_em: new Date().toISOString() }];
const drones = [{ id: 1, modelo: "Drone de teste", serial: "QA-01", status: "disponivel", bateria_pct: 87, horas_voo: 14 }];
const reports = [{ id: 1, titulo: "Inventário de validação", empresa_nome: "Atlas Logística", tipo: "mensal", status: "concluido", total_lidos: 4, total_erros: 0, criado_em: new Date().toISOString() }];
const query = async (data) => {
  const mode = scenario;
  await new Promise((resolve) => setTimeout(resolve, mode === "loading" ? 25000 : 150));
  return mode === "error" ? { success: false, message: "Servidor indisponível — cenário de teste isolado.", data: [] } : { success: true, data: mode === "empty" ? [] : data };
};
const write = async () => ({ success: false, sucesso: false, message: "Alterações de dados estão bloqueadas nesta prévia.", mensagem: "Nenhum comando é enviado ao equipamento nesta prévia." });
export const listarEmpresas = () => query(companies);
export const listarLeituras = () => query(readings);
export const leiturasPorEmpresa = (id) => query(readings.filter((item) => String(item.empresa_id) === String(id)));
export const listarOperacoes = () => query(operations);
export const listarOperadores = () => query(operators);
export const listarSetores = () => query(sectors);
export const listarAlertas = () => query(alerts);
export const listarDrones = () => query(drones);
export const listarRelatorios = () => query(reports);
export const resumoStats = async () => {
  const result = await query(readings);
  if (!result.success) return result;
  return { success: true, data: { ...computeReadingStats(result.data), empresas: scenario === "empty" ? 0 : 2, leituras: result.data.length, operacoes: scenario === "empty" ? 0 : 1, operadores: scenario === "empty" ? 0 : 1, alertas: scenario === "empty" ? 0 : 1, drones_disponiveis: scenario === "empty" ? 0 : 1, top_empresas: scenario === "empty" ? [] : [{ nome: "Atlas Logística", leituras: 3 }, { nome: "Horizonte Armazéns", leituras: 1 }] } };
};
export const backendStatus = () => scenario !== "error";
export const statusLeitura = async () => ({ sucesso: scenario !== "error", ativa: scenario === "error" ? null : false });
export const criarEmpresa = write, atualizarEmpresa = write, excluirEmpresa = write;
export const criarOperador = write, atualizarOperador = write, excluirOperador = write;
export const criarSetor = write, excluirSetor = write;
export const criarOperacao = write, setOperacaoStatus = write, excluirOperacao = write;
export const gerarRelatorio = write, excluirRelatorio = write;
export const criarAlerta = write, marcarAlertaLido = write, excluirAlerta = write;
export const criarDrone = write, atualizarDrone = write, excluirDrone = write;
export const criarLeitura = write, iniciarLeitura = write, pararLeitura = write;
